- app/models/address.rb
- app/models/cart_item.rb
- db/migrate/20220715084633_create_cart_items.rb
- db/migrate/20220715084737_create_addresses.rb
- db/schema.rb
- test/fixtures/addresses.yml
- test/fixtures/cart_items.yml
- test/models/address_test.rb
- test/models/cart_item_test.rb
cart_items・addressesのモデル作成とカラムの追加を行いました。
> make_model

- Gemfile.lock
- app/assets/stylesheets/admin/items.scss
- app/controllers/admin/items_controller.rb
- app/helpers/admin/items_helper.rb
- test/controllers/admin/items_controller_test.rb
> bundle-install

- app/assets/stylesheets/admin/accept_order_details.scss
- app/assets/stylesheets/admin/accept_orders.scss
- app/assets/stylesheets/admin/customers.scss
- app/assets/stylesheets/admin/genres.scss
- app/assets/stylesheets/admin/homes.scss
- app/controllers/admin/accept_order_details_controller.rb
- app/controllers/admin/accept_orders_controller.rb
- app/controllers/admin/customers_controller.rb
- app/controllers/admin/genres_controller.rb
- app/controllers/admin/homes_controller.rb
- app/helpers/admin/accept_order_details_helper.rb
- app/helpers/admin/accept_orders_helper.rb
- app/helpers/admin/customers_helper.rb
- app/helpers/admin/genres_helper.rb
- app/helpers/admin/homes_helper.rb
- test/controllers/admin/accept_order_details_controller_test.rb
- test/controllers/admin/accept_orders_controller_test.rb
- test/controllers/admin/customers_controller_test.rb
- test/controllers/admin/genres_controller_test.rb
- test/controllers/admin/homes_controller_test.rb
admin/homes
admin/genres
admin/customers
admin/accept_orders
admin/accept_order_detailsを作成しました
> admin側ののコントローラー作成

- app/views/admin/shared/_links.html.erb
- config/routes.rb
ルーティングの変更と、カリキュラムに載ってる削除する部分の削除を行いました。
> ルーティングの変更、不要箇所の削除

- app/controllers/admin/genres_controller.rb
- app/views/admin/genres/edit.html.erb
- app/views/admin/genres/index.html.erb
> ジャンル編集画面の作成

- app/controllers/admin/items_controller.rb
- app/views/admin/items/show.html.erb
admin/itemsの詳細ページを作成しました。
レイアウトはまだボロボロですが、とりあえず先に進めていきます。
> admin-itemsの詳細ページの作成

- app/controllers/admin/accept_order_details_controller.rb
- app/controllers/admin/accept_orders_controller.rb
- app/models/order.rb
- app/models/order_detail.rb
- app/views/admin/accept_orders/show.html.erb
- app/views/admin/homes/top.html.erb
- app/views/admin/items/index.html.erb
- app/views/admin/items/new.html.erb
- app/views/admin/items/show.html.erb
order.rbとorder_detail.rbにenumの追記を行いました。
注文履歴詳細のページ作成後、注文ステータスの部分まで、
あってるかわかりませんが、記述しました。
> 注文履歴詳細作成途中

- app/views/public/registrations/new.html.erb
> 新規会員登録画面の日本語化＆レイアウト

- app/controllers/public/orders_controller.rb
- app/models/address.rb
- app/models/customer.rb
- app/views/public/cart_items/index.html.erb
- app/views/public/orders/confirm.html.erb
- app/views/public/orders/index.html.erb
- app/views/public/orders/new.html.erb
OrderコントローラーでOderDetailにCartItemの情報が1レコードしか保存されてなかったので修正しました。
order/newページの文字はf.labelで表示させていいんでしょうか。何かいい案があれば教えてください。
> Orderコントローラーの修正 Viewページの編集

- app/controllers/public/cart_items_controller.rb
- app/controllers/public/orders_controller.rb
- app/models/order.rb
- app/models/order_detail.rb
- app/views/public/orders/confirm.html.erb
- app/views/public/orders/new.html.erb
- app/views/public/orders/show.html.erb
> 注文履歴詳細画面完成

- app/views/public/cart_items/index.html.erb
> カート内商品一覧画面のレイアウト

- app/controllers/admin/accept_order_details_controller.rb
- app/controllers/admin/accept_orders_controller.rb
- app/models/item.rb
- app/models/order.rb
- app/models/order_detail.rb
- app/views/admin/accept_orders/show.html.erb
- config/locales/ja.yml
> 注文詳細画面また途中ですが

- app/controllers/application_controller.rb
- app/controllers/public/cart_items_controller.rb
- config/initializers/devise.rb
> ヘッダー：ログアウト機能

- app/views/public/orders/new.html.erb
> 注文情報入力画面のレイアウト

- app/views/admin/sessions/new.html.erb
- app/views/public/orders/new.html.erb
管理者ログイン画面のレイアウトを修正しました。
（public/orders/new.htmlから一部同じ箇所をコピーしています。）
> 管理者ログイン画面のレイアウト

- app/controllers/admin/accept_order_details_controller.rb
- app/controllers/admin/accept_orders_controller.rb
- app/views/admin/accept_orders/show.html.erb
> 注文ステータスと製作ステータスの連動

- app/controllers/admin/accept_orders_controller.rb
- app/views/admin/accept_orders/show.html.erb
> 名前を押してlink先に飛べるようにした。

- app/views/admin/homes/top.html.erb
> 注文履歴一覧画面のレイアウト

- app/views/admin/items/edit.html.erb
商品編集画面(admin/items/edit)のレイアウトを調整しました。
> 商品編集画面のレイアウト

- app/views/admin/customers/edit.html.erb
- app/views/admin/customers/show.html.erb
> 顧客詳細画面のレイアウト
